# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp, the target density has been given.
#' @param num The number of samples. Default is \code{10000}.
#' @param a Parameter of density. Default is \code{1}.
#' @param b Parameter of density. Default is \code{1}.
#' @param n Parameter of density. Default is \code{100}.
#' @return A \code{matrix}, the number of rows is the param num and the numberof colmuns is 2.
#' @examples
#' \dontrun{
#' c.chain <- bi_chain_cpp()
#' plot(c.chain)
#' }
#' @export
bi_chain_cpp <- function(num = 10000L, a = 1L, b = 1L, n = 100L) {
    .Call('_StatComp21077_bi_chain_cpp', PACKAGE = 'StatComp21077', num, a, b, n)
}

#' @title example
#' @description A Gibbs sampler using Rcpp, the target density has been given.
#' @return Constant matrix.
#' @export
myfun <- function() {
    .Call('_StatComp21077_myfun', PACKAGE = 'StatComp21077')
}

