# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp, the target density has been given.
#' @param num The number of samples. Default is \code{10000}.
#' @param a Parameter of density. Default is \code{1}.
#' @param b Parameter of density. Default is \code{1}.
#' @param n Parameter of density. Default is \code{100}.
#' @return A \code{matrix}, the number of rows is the param num and the numberof colmuns is 2.
#' @examples
#' \dontrun{
#' c.chain <- bi_chain_cpp()
#' plot(c.chain)
#' }
#' @export
bi_chain_cpp <- function(num = 10000L, a = 1L, b = 1L, n = 100L) {
    .Call('_StatComp21077_bi_chain_cpp', PACKAGE = 'StatComp21077', num, a, b, n)
}

#' @title gamma fit approximate newton method
#' @description fit gamma model with approximate newton method.
#' @param x Input matrix, of dimension \eqn{n \times p}; each row is an observation vector and each column is a predictor/feature/variable.
#' @param y The response variable, of \code{n} observations.
#' @param weights Observation weights.
#' @param beta Linear coefficient.
#' @param coef0 Intercept.
#' @param lambda L2 penalty coefficient.
#' @return NULL
#' @export
gamma_fit_approximate_newton_method <- function(x, y, weights, beta, coef0, lambda) {
    invisible(.Call('_StatComp21077_gamma_fit_approximate_newton_method', PACKAGE = 'StatComp21077', x, y, weights, beta, coef0, lambda))
}

